// <auto-generated />
namespace SimplyHireWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class users_skills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_skills));
        
        string IMigrationMetadata.Id
        {
            get { return "202101022156422_users_skills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
